version: "3"
services:
  web:
    build: ./customer_transaction_prediction_frontend
    ports:
      - "3000:3000"
    env_file: .env
  
  backend:
    build: ./customer_transaction_prediction_backend
    ports:
      - "8000:8000"
    env_file: .env 